name: Bicep DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Install Checkov
      run: pip install checkov

    - name: Build Bicep to ARM JSON
      run: az bicep build --file main.bicep --outdir ./out

    - name: Run Checkov Security Scan
      run: checkov -f ./out/main.json

    - name: Deploy Bicep to Azure
      run: |
        az deployment group create \
          --resource-group my-resource-group \
          --template-file main.bicep \
          --parameters @parameters.json
